version: '3.1'

services:
  oracle:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle18c
    ports:
      - "1521:1521"   # Porta padrão para Oracle SQL*Net
      - "5500:5500"   # Porta padrão para Oracle Enterprise Manager
    environment:
      ORACLE_PWD: "YourPassword123"  # Senha para o usuário SYS e SYSTEM
    volumes:
      - oracle_data:/opt/oracle/oradata   # Persistência dos dados

volumes:
  oracle_data:
    driver: local
