version: "3.2"
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    restart: always
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888 server.2=zookeeper-replica:2888:3888

  zookeeper-replica:
    image: zookeeper
    hostname: zookeeper-replica
    restart: always
    volumes:
      - ./zoo2/data:/data
      - ./zoo2/datalog:/datalog
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper:2888:3888 server.2=zookeeper-replica:2888:3888
  # microservice:
  #     build: ./spring-boot-microservice-1/
  #     hostname: microservice
  #     ports:
  #       - "8080:8080"
  #     volumes:
  #         - ./ms1/.m2:/root/.m2
  #     links:
  #       - zookeeper
  #     depends_on:
  #       - zookeeper
  # microservice_2:
  #     build: ./spring-boot-microservice-2/
  #     hostname: microservice-2
  #     ports:
  #       - "8180:8080"
  #     volumes:
  #         - ./ms2/.m2:/root/.m2
  #     links:
  #       - zookeeper
  #       - microservice
  #     depends_on:
  #       - zookeeper
