version: "3.8"
services:
  mysql:
    image: mysql:8.0.34
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: 'example'
      MYSQL_USER: 'user_db'
      MYSQL_PASSWORD: 'user_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - mysql_net
    volumes:
      - "${PWD}/data:/var/lib/mysql"
networks:
  mysql_net:
    driver: bridge