version: "3.6"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="mongo-user"
      - MONGODB_PASS="mongo-pass"
    volumes:
      - /data/db
