version: "3.6"
services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=spring-in-action
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=GMT-3
    volumes:
      - "~/Documentos/docker_volumes/postgresql:/var/lib/postgresql/data"
    restart: always
networks:
  postgres:
    driver: bridge
